[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (where the built files are located)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirects for SPA routing (if needed in the future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables that need to be set in Netlify dashboard:
# VITE_MAPBOX_ACCESS_TOKEN=your_actual_mapbox_token_here
# VITE_APP_TITLE=Synergy - LA Infrastructure Analysis
# VITE_APP_DESCRIPTION=Visualizing Capital Improvement Projects and EV Chargers in Los Angeles 